### ISSUE TITLE
本地build部署(采用Nginx)后，部分页面404

### ISSUE THREAD

**Issue by JunzhouLiu** [spencerwooo/portfolio#10]
例如`xxxx.yy/social`页面，直接访问会404，只能从`home`页面点击进入，进入后刷新也会404，而且404页面还是nginx的页面，非预设的404。

本地run server 没有类似的问题产生。

因为不熟悉vue，猜测可能是路由采用了history mode的问题。

更新：
经过一番搜索，在`nginx.conf`配置中增加`try_files $uri $uri/ /index.html;`即可。

**Comment by spencerwooo** [comment]
👍 解决了就好
