### ISSUE TITLE
缺少404页面

### ISSUE THREAD

**Issue by kidonng** [spencerwooo/portfolio#5]
您在少数派的部分旧文（[例子](https://sspai.com/post/43674)）中的博文链接已失效，点击链接打开的页面比较令人迷惑：
![image](https://user-images.githubusercontent.com/44045911/83374179-697bdd00-a3fd-11ea-9ed1-c01cff875155.png)
加入404页面（或者跳转到博文存档）会比较友好。

**Comment by spencerwooo** [comment]
Resolved.
