### ISSUE TITLE
手机端问题

### ISSUE THREAD

**Issue by Royce003** [spencerwooo/portfolio#7]
手机端 main-navbar 点击不会自动收回

并且点击红色区域有反馈，但不跳转
![image](https://user-images.githubusercontent.com/57910033/84895373-cd2c2880-b0d4-11ea-93e3-29567c717a01.png)

**Comment by spencerwooo** [comment]
- Q1: Upstream issue & is designed intentionally.
- Q2: Can't reproduce.
